# Definir los anchors primero
x-spark-common: &spark-common
  image: custom-spark:latest
  networks:
    - data-stack
  environment:
    - SPARK_MODE=master
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  networks:
    - data-stack
  environment:
    - AIRFLOW_CONN_SPARK_DEFAULT=spark://spark-master:7077
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
    - AIRFLOW__CORE__LOAD_EXAMPLES=false
    - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./jobs:/opt/airflow/jobs
  depends_on:
    - postgres

services:
  # Spark Master
  spark-master:
    <<: *spark-common
    container_name: spark_master_data_stack_FHBD
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"  # Interfaz web de Spark
      - "7077:7077"  # Puerto maestro de Spark
    environment:
      - SPARK_MODE=master
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin  # Minio username
      - AWS_SECRET_ACCESS_KEY=password  # Minio password  
    volumes: 
      - ./jobs:/opt/bitnami/spark/jobs

  # Spark Worker
  spark-worker:
    <<: *spark-common
    container_name: spark_worker_data_stack_FHBD
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_MASTER_URL=spark://spark-master:7077
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin  # Minio username
      - AWS_SECRET_ACCESS_KEY=password  # Minio password
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      
  # Jupyter Notebook con PySpark
  jupyter:
    image: custom-spark:latest
    container_name: jupyter_notebook_data_stack_FHBD
    ports:
      - "8888:8888"  # Acceso a Jupyter Notebook
    volumes:
      - ./notebooks:/opt/bitnami/spark/notebooks
      - ./requirements.txt:/tmp/requirements.txt
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
    networks:
      - data-stack
    depends_on:
      - spark-master
      - spark-worker
    command: >
      bash -c "
      pip install --no-cache-dir -r /tmp/requirements.txt &&
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root 
      --NotebookApp.token='' --NotebookApp.password='' 
      --notebook-dir=/opt/bitnami/spark/notebooks"

  # Base de datos PostgreSQL para Airflow
  postgres:
    image: postgres:14.0
    container_name: postgres_data_stack_FHBD
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - data-stack
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Inicialización de Airflow
  init-airflow:
    <<: *airflow-common
    container_name: init_airflow_data_stack_FHBD
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --firstname Admin --lastname User 
      --role Admin --email admin@example.com --password admin
      "
    depends_on:
      - postgres

  # Servidor web de Airflow
  webserver:
    <<: *airflow-common
    container_name: airflow_webserver_data_stack_FHBD
    command: webserver
    ports:
      - "8080:8080"  # UI de Airflow
    depends_on:
      - init-airflow
   
  # Scheduler de Airflow
  scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler_data_stack_FHBD
    command: scheduler
    depends_on:
      - init-airflow

  # MinIO (Almacenamiento S3-compatible)
  minio:
    image: minio/minio
    container_name: minio_docker_data_stack_FHBD
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # Consola de MinIO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - data-stack

  # Nessie Catalog Server
  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie_data_stack_FHBD
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_HTTP_PORT=19120
      - QUARKUS_LOG_CONSOLE_FORMAT=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n
      - QUARKUS_LOG_LEVEL=INFO
    volumes:
      - ./nessie-data:/nessie/data
    ports:
      - "19120:19120"
    networks:
      - data-stack

  # Dremio
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
    container_name: dremio_data_stack_FHBD
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    networks:
      - data-stack

# Definiciones de red y volúmenes
networks:
  data-stack:
    driver: bridge

volumes:
  postgres_data: